### ISSUE TITLE
Validating Webhook accounts.config.kiosk.sh

### ISSUE THREAD

**Issue by FabianKramm** [kiosk-sh/kiosk#2]
We need a validating webhook for accounts.config.kiosk.sh, that checks for the following things:
- Create / Update:
   - Space Template spec.account has to be unfilled

**Comment by rahulchheda** [comment]
Is this issue still available? @FabianKramm ?

**Comment by rahulchheda** [comment]
Would like to start working on this.

**Comment by FabianKramm** [comment]
@rahulchheda yes there is still a check missing if the account field in the space template is unfilled currently, would be great if you would open a pr for this!

**Comment by FabianKramm** [comment]
implemented by #64
