### ISSUE TITLE
Validating Webhook accountquotas.config.kiosk.sh

### ISSUE THREAD

**Issue by FabianKramm** [kiosk-sh/kiosk#34]
AccountQuota needs a validating webhook to check for the following things:
- Create/Update:
  - Ensure valid resource list (currently you can specify invalid resources), basically do the same checks as ResourceQuota is doing

**Comment by rahulchheda** [comment]
Is this issue still available? @FabianKramm ?

**Comment by FabianKramm** [comment]
@rahulchheda yes this is still available, currently the check if the specified resources are valid is still missing, would be great if you would open a pr for this!

**Comment by rahulchheda** [comment]
@FabianKramm , can you add context to this issue also, so I can take this up aswell?

**Comment by FabianKramm** [comment]
@rahulchheda sure, in essence this issue is similar to #2, however this time we want to validate the AccountQuota resources (`spec.quota`). We want to do the exact same checks as kubernetes does for ResourceQuota `spec`, hence I think the best way is to reuse most of the validation kubernetes does for this type (corev1.ResourceQuotaSpec) if possible, you can take a look how kubernetes does it here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L5339 .  

I think the best idea would be to copy over the relevant code from them (because we do not want github.com/kubernetes/kubernetes as a dependency, see https://github.com/kubernetes/kubernetes/issues/80339#issuecomment-513293370 for more details) and change their internal *core.ResourceQuotaSpec type to the one we use *corev1.ResourceQuotaSpec.
