### ISSUE TITLE
User can't create TemplateInstance in its own Space

### ISSUE THREAD

**Issue by Jabbo16** [kiosk-sh/kiosk#42]
I followed the `README` steps and everything works fine until the part when the users are given access to view `Template` and to create `TemplateInstance` resources.

Im using current latest release of Kiosk.

```shell
~/kiosk_test $ kubectl get templates.config.kiosk.sh --as=john
NAME                 AGE
redis                8m57s
space-restrictions   9m2s

~/kiosk_test $ kubectl apply -f https://raw.githubusercontent.com/kiosk-sh/kiosk/master/examples/rbac-template-instance-admin.yaml
clusterrole.rbac.authorization.k8s.io/kiosk-template-admin unchanged

~/kiosk_test $ kubectl apply --as=john -n johns-space -f https://raw.githubusercontent.com/kiosk-sh/kiosk/master/examples/template-instance.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "config.kiosk.sh/v1alpha1, Resource=templateinstances", GroupVersionKind: "config.kiosk.sh/v1alpha1, Kind=TemplateInstance"
Name: "redis-instance", Namespace: "johns-space"
Object: &{map["apiVersion":"config.kiosk.sh/v1alpha1" "kind":"TemplateInstance" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"redis-instance" "namespace":"johns-space"] "spec":map["template":"redis"]]}
from server for: "https://raw.githubusercontent.com/kiosk-sh/kiosk/master/examples/template-instance.yaml": templateinstances.config.kiosk.sh "redis-instance" is forbidden: User "john" cannot get resource "templateinstances" in API group "config.kiosk.sh" in the namespace "johns-space"
```

**Comment by LukasGentele** [comment]
@Jabbo16 Thanks for reporting this! This is actually not a bug but just a problem in the example. The account `johns-account` does not define `spec.space.clusterRole: kiosk-space-admin`, so Spaces are not deletable and account users are not able to manage templateinstances within the Spaces. So, instead of using `johns-space` which belongs to `johns-account`, the example should use a Space that belongs to `johns-account-deletable-spaces`, e.g. `space-2`.

So, if you still have `space-2`, does this work for you? 
```
kubectl apply --as=john -n space-2 -f https://raw.githubusercontent.com/kiosk-sh/kiosk/master/examples/template-instance.yaml
```

**Comment by Jabbo16** [comment]
Oh yeah Its my bad then, I missed that part as I dont need deletable spaces (users also just need only 1 namespace), I was wondering where the rolebinding was defined and overlooked that part.

Closing the issue then. Thanks!

**Comment by LukasGentele** [comment]
Great. The README is actually misleading in this section and the example is not correct. We should update it to `space-2` and make a note about this. Thanks for spotting this!

PS: If you don't want Spaces to be deletable but still want users to be able to work with TemplateInstances, you can also use `spec.space.clusterRole: kiosk-template-admin` in the account configuration.
