### ISSUE TITLE
can't create template instance based on helm

### ISSUE THREAD

**Issue by allamand** [kiosk-sh/kiosk#67]
Hi,

thanks for the great work you've done with this repo!

While testing the helm based instance template, I'm ending with this error in kiosk controller, using the redis from the Readme

```
Template instance dev-space3/redis-instance failed: Error during helm template: Failed to unmarshal manifest: error unmarshaling JSON: Object 'Kind' is missing in '{\"WARNING\":\"This chart is deprecated\"}'"}
````

also is it possible to have a mix of manifests + helm in the template ?

thanks

**Comment by FabianKramm** [comment]
@allamand thanks for opening! I fixed the example yaml, it should work now!
